### ISSUE TITLE
Should provide options setter for time limit

### ISSUE THREAD

**Issue by justkexit** [geekydatamonkey/simple-ldap-search#7]
Some search operations in LDAP are heavy and default time limit is not enough

**Comment by geekydatamonkey** [comment]
Could you provide some more info about this? A reduced test case would be helpful.

The [default timeout for ldapjs is infinity](http://ldapjs.org/client.html), so I'm wondering if there's a different issue at play?

**Comment by geekydatamonkey** [comment]
Closing this for now. Please feel free to reopen if there's more info.
